function schema = phase3_observation_v2_schema(cfg,version)
%phase3_observation_v2_schema Fixed engineering scales, not calibrated safety limits.
    if nargin < 2
        version = 'observation_v2_dynamic_health_candidate_v1';
    end
    version = validatestring(version,{'observation_v2_dynamic_health_candidate_v1', ...
        'observation_v2_dynamic_health_candidate_v2'});
    base = ["tracking_window","effort_window","battery_margin","progress", ...
        "requested_v","requested_a","executed_v","executed_a", ...
        "R1","R2","R3","previous_Ieq","schedule_margin","time_remaining"];
    physical = ["velocity_x","velocity_y","velocity_z", ...
        "velocity_error_x","velocity_error_y","velocity_error_z", ...
        "orientation_angle","orientation_skew_x","orientation_skew_y","orientation_skew_z", ...
        "omega_x","omega_y","omega_z","rotation_orthogonality", ...
        "foot_relative_norm_1","foot_relative_norm_2","foot_relative_norm_3","foot_relative_norm_4", ...
        "force_norm_1","force_norm_2","force_norm_3","force_norm_4"];
    fsm = ["stance_1","stance_2","stance_3","stance_4", ...
        "swing_1","swing_2","swing_3","swing_4", ...
        "phase_fraction_1","phase_fraction_2","phase_fraction_3","phase_fraction_4", ...
        "phase_duration_1","phase_duration_2","phase_duration_3","phase_duration_4"];
    action = ["candidate_dR1","candidate_dR2","candidate_dR3","candidate_gamma_v","candidate_gamma_a", ...
        "applied_dR1","applied_dR2","applied_dR3","applied_gamma_v","applied_gamma_a"];
    solverClasses = ["solver_success","numerical_solver_failure_recovered", ...
        "numerical_solver_failure","mathematical_constraint_infeasible", ...
        "invalid_state","unclassified_solver_failure","other"];
    solver = ["solver_iterations","solver_minimum_margin","solver_wall_seconds","class_"+solverClasses];
    flags = ["dynamic_state_valid","has_solver_history","has_fsm_history", ...
        "has_action_history","has_solver_margin"];
    names = [base physical fsm action solver flags].';
    actionScale = [cfg.DR_MAX*ones(3,1);1;1];
    scales = [ones(14,1);ones(14,1);0.5*ones(4,1);100*ones(4,1); ...
        ones(12,1);0.5*ones(4,1);actionScale;actionScale;100;1;0.01;ones(12,1)];
    identity = startsWith(names,"stance_") | startsWith(names,"swing_") | ...
        startsWith(names,"class_") | ismember(names,flags);
    assert(numel(names)==numel(scales),'observationV2:Schema','Feature scales differ from names.');
    rawIndices = (1:numel(names)).';
    if strcmp(version,'observation_v2_dynamic_health_candidate_v2')
        keep = names~="solver_wall_seconds";
        rawIndices = rawIndices(keep);
        names = names(keep);
        scales = scales(keep);
        identity = identity(keep);
    end
    schema = struct('version',version,'raw_indices',rawIndices, ...
        'names',names,'scales',scales,'identity_transform',identity, ...
        'legacy_indices',[1 2 3 4 6 7 8 9 10 11 12 19], ...
        'solver_classes',solverClasses,'dimension',numel(names),'training_promoted',false, ...
        'continuous_transform','asinh(raw/scale), without clipping', ...
        'missing_rule','Raw NaN retained in audit; encoded zero with explicit context/validity flags.', ...
        'normalization_basis','Fixed engineering units; no fitted statistics or calibrated safety thresholds.');
end
