function execution = resolve_supervisory_action(candidate, previous, cfg, lowerR, upperR)
%resolve_supervisory_action Apply the RL clipping, rate limit, and governor.
% previous supplies last_R, v_req, a_req, v_exec, prev_gamma_v and
% prev_gamma_a. previous_applied_action is optional only for legacy logs.

    arguments
        candidate (5,1) double {mustBeReal, mustBeFinite}
        previous (1,1) struct
        cfg (1,1) struct
        lowerR (3,1) double {mustBePositive, mustBeFinite}
        upperR (3,1) double {mustBePositive, mustBeFinite}
    end
    required = {'last_R','v_req','a_req','v_exec','prev_gamma_v','prev_gamma_a'};
    if ~all(isfield(previous, required))
        error('resolve_supervisory_action:MissingHistory', ...
            'Supply R, requested/executed commands, and previous applied gammas.');
    end
    validateattributes(previous.last_R, {'double'}, ...
        {'real','finite','positive','numel',3});
    validateattributes([previous.v_req, previous.a_req, previous.v_exec, ...
        previous.prev_gamma_v, previous.prev_gamma_a], {'double'}, {'real','finite'});
    if any(lowerR > upperR)
        error('resolve_supervisory_action:InvalidBounds', ...
            'Each lower R bound must be no greater than its upper bound.');
    end
    dR = min(max(candidate(1:3), -cfg.DR_MAX), cfg.DR_MAX);
    gammaV = candidate(4);
    if isfield(cfg, 'DGAMMA_V_MAX')
        gammaV = min(max(gammaV, previous.prev_gamma_v-cfg.DGAMMA_V_MAX), ...
            previous.prev_gamma_v+cfg.DGAMMA_V_MAX);
    end
    gammaV = min(max(gammaV, cfg.GAMMA_V_MIN), cfg.GAMMA_V_MAX);
    gammaA = min(max(candidate(5), cfg.GAMMA_A_MIN), cfg.GAMMA_A_MAX);
    oldR = previous.last_R(:);
    newR = min(max(oldR.*(1+dR), lowerR), upperR);
    [velocity, acceleration, governor] = apply_command_governor( ...
        previous.v_req, previous.a_req, gammaV, gammaA, cfg);
    actualDR = newR./oldR - 1;
    priorAction = [nan(3,1); previous.prev_gamma_v; previous.prev_gamma_a];
    if isfield(previous, 'previous_applied_action')
        priorAction = previous.previous_applied_action(:);
        validateattributes(priorAction, {'double'}, {'real','finite','numel',5});
    end
    execution = struct('schema_version', "action_v2_rate_limited", ...
        'candidate_action', candidate, 'dR_clipped', dR, ...
        'gamma_v_raw', candidate(4), 'gamma_a_raw', candidate(5), ...
        'gamma_v_applied', gammaV, 'gamma_a_applied', gammaA, ...
        'R_before', oldR, 'R_applied', newR, 'dR_effective', actualDR, ...
        'R_lower_bound', lowerR, 'R_upper_bound', upperR, ...
        'applied_action', [actualDR; gammaV; gammaA], ...
        'previous_applied_action', priorAction, ...
        'previous_action_complete', all(isfinite(priorAction)), ...
        'v_req', previous.v_req, 'a_req', previous.a_req, ...
        'v_exec', velocity, 'a_exec', acceleration, ...
        'delta_gamma_v_applied', gammaV-previous.prev_gamma_v, ...
        'delta_v_exec', velocity-previous.v_exec, ...
        'gamma_rate_limited', gammaV ~= candidate(4), ...
        'R_saturated', any(newR ~= oldR.*(1+dR)), 'governor', governor);
end
