function report = run_phase3_map_validation(outputRoot)
%run_phase3_map_validation Check three captured candidates without safety promotion.
    source = bootstrap_RF_MPC_RL();
    loaded = load(fullfile(source,'rlEnv_MPC_R.mat'),'cfg','initial_R','lower_abs','upper_abs');
    cfg = loaded.cfg;
    state = initialize_mpc_replay_state(cfg,0);
    state.R = loaded.initial_R(:);
    state.supervisory_state.last_R = state.R;
    metadata = struct('run_id','map_action_path_validation','run_type','viability_map_validation', ...
        'monitor_root',fullfile(fileparts(source),'RL-MPC-Monitor'),'seed',cfg.RNG_SEED, ...
        'observation_schema_version','not_used_map','reward_version',cfg.REWARD.version, ...
        'solver_strategy','default','source_policy','three_controlled_candidates');
    writer = ExactStateDataset(outputRoot,cfg,metadata);
    bases = struct('base_label','nominal_reset','policy_source','mission_gamma_reset');
    samples = table((1:3).',repmat("gamma_heatmap",3,1),repmat("fixed_R",3,1), ...
        zeros(3,1),zeros(3,1),zeros(3,1), ...
        [cfg.GAMMA_V_MISSION;cfg.GAMMA_V_MAX;cfg.GAMMA_V_MIN], ...
        repmat(cfg.GAMMA_A_MIN,3,1),'VariableNames', ...
        {'action_id','sample_type','profile','dR1','dR2','dR3','gamma_v','gamma_a'});
    result = build_dynamic_viability_map({state},bases,samples,cfg, ...
        fullfile(outputRoot,'analysis'),0.05,writer, ...
        struct('lower',loaded.lower_abs,'upper',loaded.upper_abs));
    assert(writer.RowCount == 15, 'run_phase3_map_validation:Coverage','Expected 15 captured MPC solves.');
    assert(~any(result.map.safe_action), 'run_phase3_map_validation:PrematureApproval', ...
        'Provisional threshold results cannot authorize policy actions.');
    assert(abs(result.map.gamma_v_applied(2)-min(cfg.GAMMA_V_MAX, ...
        cfg.GAMMA_V_MISSION+cfg.DGAMMA_V_MAX)) < 1e-12, ...
        'run_phase3_map_validation:RateLimit','Map bypassed the gamma rate limiter.');
    writer.finish('map_action_and_label_validation_complete');
    report = validate_exact_state_dataset(outputRoot);
    report.map = result.map;
    disp(result.map(:,{'gamma_v_raw','gamma_v_applied','v_exec','viability_class', ...
        'safe_action','within_envelope_at_horizon','recovery_candidate'}));
end
