function allowed = should_rescue_qp(primary)
%should_rescue_qp Require positive feasibility evidence before numeric rescue.
    allowed = ~primary.success && ...
        string(primary.classification) == "numerical_solver_failure" && ...
        isfield(primary.phase1, 'phase1_z') && ...
        ~isempty(primary.phase1.phase1_z) && ...
        all(isfinite(primary.phase1.phase1_z)) && ...
        any(string(primary.phase1.classification) == ...
        ["linearly_feasible", "solver_difficulty_or_objective_numerics"]);
end
