function rows = supervisory_action_table(executions)
%supervisory_action_table Flatten candidate/applied transformations for dataset indexes.

    arguments
        executions (:,1) cell
    end
    count = numel(executions);
    values = nan(count, 30);
    for index = 1:count
        item = executions{index};
        values(index,:) = [item.candidate_action(:).', ...
            item.applied_action(:).', item.R_applied(:).', ...
            item.v_req, item.a_req, item.v_exec, item.a_exec, ...
            item.previous_applied_action(:).', ...
            item.delta_gamma_v_applied, item.delta_v_exec, ...
            item.dR_clipped(:).', item.R_saturated, ...
            item.gamma_rate_limited, item.previous_action_complete];
    end
    names = {'actor_candidate_dR1','actor_candidate_dR2','actor_candidate_dR3', ...
        'gamma_v_raw','gamma_a_raw','dR1_effective','dR2_effective','dR3_effective', ...
        'gamma_v_applied','gamma_a_applied','R1_applied','R2_applied','R3_applied', ...
        'v_req','a_req','v_exec','a_exec', ...
        'previous_applied_dR1','previous_applied_dR2','previous_applied_dR3', ...
        'previous_applied_gamma_v','previous_applied_gamma_a', ...
        'delta_gamma_v_applied','delta_v_exec','dR1_clipped','dR2_clipped', ...
        'dR3_clipped','R_saturated','gamma_rate_limited','previous_action_complete'};
    rows = array2table(values, VariableNames=names);
end
