function train_RL_MPC()
    S = load('rlEnv_MPC_R.mat','env','agent','cfg');
    env   = S.env;
    agent = S.agent;

    trainOpts = rlTrainingOptions( ...
        'MaxEpisodes', 600, ...
        'MaxStepsPerEpisode', 10, ...
        'ScoreAveragingWindowLength', 20, ...
        'Verbose', true, ...
        'Plots', 'training-progress', ...
        'StopTrainingCriteria','EpisodeReward', ... % improvement-based, can cross zero
        'StopTrainingValue', 50);

    stats = train(agent, env, trainOpts);

    save('final_RL_agent.mat','agent','stats');
    disp('Training complete.');
end
