function condition = validate_phase3_initial_condition(condition)
%validate_phase3_initial_condition Validate an explicit reset-only scenario.
% These are experiment coordinates, not a physically calibrated safe envelope.
    fields = {'schema','id','rotation_vector_body_rad', ...
        'angular_velocity_body_delta_rad_s','linear_velocity_world_delta_m_s'};
    assert(isstruct(condition) && isscalar(condition) && ...
        isequal(sort(fieldnames(condition)),sort(fields.')), ...
        'phase3InitialCondition:Schema','An exact initial-condition schema is required.');
    assert(isequal(condition.schema,'reset_body_perturbation_v1') || ...
        isequal(condition.schema,"reset_body_perturbation_v1"), ...
        'phase3InitialCondition:Schema','Unsupported initial-condition version.');
    assert((ischar(condition.id) && isrow(condition.id)) || ...
        (isstring(condition.id) && isscalar(condition.id) && ~ismissing(condition.id)), ...
        'phase3InitialCondition:Id','A scalar scenario ID is required.');
    condition.id = char(condition.id);
    assert(~isempty(regexp(condition.id,'^[A-Za-z0-9][A-Za-z0-9_.-]*$','once')), ...
        'phase3InitialCondition:Id','Use a nonempty ASCII scenario identifier.');
    condition.schema = 'reset_body_perturbation_v1';
    for name = fields(3:end)
        validateattributes(condition.(name{1}),{'double'}, ...
            {'vector','numel',3,'finite','real'},mfilename,name{1});
        condition.(name{1}) = condition.(name{1})(:);
    end
    assert(norm(condition.rotation_vector_body_rad)<=pi, ...
        'phase3InitialCondition:RotationRange','Use a principal rotation vector with norm <= pi.');
end
