function e = finishExposure(a)
%finishExposure Finalize explicit known and missing physical/current exposure.
    assert(~isempty(a) && a.attempts>0,'phase3reward:Empty','No captured decision rows.');
    duration = a.dt*a.integrated_steps;
    coverage = a.dt*a.finite_steps;
    full = a.known;
    full(a.finite_steps~=a.integrated_steps) = NaN;
    sampled = NaN;
    if a.sample_count>=2
        sampled = a.sampled_charge;
    end
    e = struct('schema','reward_exposure_components_v1','attempts',a.attempts, ...
        'integrated_duration_s',duration,'physical_names',["orientation","omega","velocity_error"], ...
        'known_squared_integrals',a.known,'full_squared_integrals',full, ...
        'finite_coverage_s',coverage,'missing_coverage_s',duration-coverage, ...
        'physical_exposure_observed',duration>0,'physical_complete',all(isfinite(full)), ...
        'current_sample_count',a.sample_count,'current_pair_observed',a.sample_count>=2, ...
        'within_window_sampled_charge_As',sampled,'adjacent_sample_charge_As',a.adjacent_charge, ...
        'adjacent_sample_support_s',a.adjacent_support, ...
        'unsupported_current_duration_s',max(0,duration-a.adjacent_support), ...
        'bridged_gap_count',a.gap_count,'bridged_gap_duration_s',a.gap_duration, ...
        'bridged_gap_charge_As',a.gap_charge,'full_window_charge_claim',false,'training_promoted',false, ...
        'scope','Streaming reduction of captured rows; known partial integrals do not impute missing exposure. Within-decision current support excludes startup, gaps and endpoint tails; booked cross-decision charge is separate.');
end
