function chunk = finishChunk(a,after)
%finishChunk Link row-derived accounting to the captured post-chunk state.
    assert(a.attempts>0 && (a.reason~="horizon_complete" || a.attempts==a.expected_steps), ...
        'phase3window:Truncated','A normal chunk must contain every requested attempt.');
    assert(isequaln(after.Xt,a.last_state.Xt) && isequaln(after.Ut,a.last_state.Ut) && ...
        after.t==a.last_time && ...
        isequal(after.current_time(:),[a.before.current_time(:);a.sample_times]) && ...
        isequal(after.current_total(:),[a.before.current_total(:);a.sample_currents]), ...
        'phase3window:Endpoint','Post-chunk state/current history differs from captured rows.');
    assert(a.reason~="integration_exception", ...
        'phase3window:Exception','An integration exception is not an ordinary supervisory transition.');
    out = struct('terminal_reason',a.reason,'completed_horizon',a.reason=="horizon_complete" || ...
        (a.reason=="mission_target_reached" && a.integrated_steps==a.expected_steps), ...
        'requested_duration_s',a.requested_duration,'integrated_steps',a.integrated_steps, ...
        'qp_solve_count',a.attempts,'qp_failed_count',a.failed_steps, ...
        'tracking_error_sum',a.tracking_sum,'control_effort_sum',a.effort_sum, ...
        'fsm_end',a.last_FSM,'stance_duration_end_s',a.last_stance, ...
        'charge_As',localCharge(after)-localCharge(a.before), ...
        'trace',struct('solver_classification',repmat("numerical_solver_failure_recovered",a.recovered_events,1)));
    chunk = struct('before',a.before,'after',after,'control',a.control,'out',out,'context',a.context);
end

function value = localCharge(state)
    value = 0;
    if numel(state.current_time)>=2
        value = trapz(state.current_time,abs(state.current_total));
    end
end
