function exposure = fromSteps(steps,dt)
%fromSteps Preserve observed costs and missing exposure.
% This is not a finite reward or a missing-data imputation policy. Current
% support is restricted to this window; cross-window booked charge is separate.
    validateattributes(dt,{'double'},{'scalar','real','finite','positive'});
    names = ["orientation","omega","velocity_error"];
    fields = ["time_before","time_after","integrated","success", ...
        "current_sample_committed","current_sample_time","current_sample_A", ...
        names+"_before",names+"_after"];
    assert(istable(steps) && height(steps)>0 && ...
        all(ismember(fields,string(steps.Properties.VariableNames))), ...
        'rewardExposure:Fields','Require a nonempty captured step table.');
    n = height(steps);
    assert(all(arrayfun(@(f) size(steps.(f),2)==1,fields)), ...
        'rewardExposure:Fields','Each captured field must be a scalar column.');
    flags = [steps.integrated,steps.success,steps.current_sample_committed];
    assert(isreal(flags) && all(flags==0 | flags==1,'all'), ...
        'rewardExposure:Flags','Flags must be explicit logical values.');
    integrated = logical(steps.integrated);
    committed = logical(steps.current_sample_committed);
    times = [steps.time_before;steps.time_after];
    tol = max(1e-10,64*eps(max([1;abs(times)])));
    assert(isreal(times) && all(isfinite(times)) && all(times>=0) && ...
        all(abs(diff(steps.time_before)-dt)<=tol) && ...
        all(abs(steps.time_after-steps.time_before-dt*integrated)<=tol), ...
        'rewardExposure:Time','Require finite contiguous MPC integration times.');
    assert(all(integrated(1:end-1)) && ~any(integrated & ~steps.success) && ...
        ~any(committed & ~integrated), ...
        'rewardExposure:Terminal','Only the final attempt may be unintegrated.');
    duration = dt*nnz(integrated);
    partial = zeros(1,3);
    coverage = zeros(1,3);
    full = nan(1,3);
    for k = 1:3
        before = steps.(names(k)+"_before");
        after = steps.(names(k)+"_after");
        assert(isreal([before;after]) && ~any([before;after]<0), ...
            'rewardExposure:Magnitude','Require nonnegative magnitudes or unavailable values.');
        available = integrated & isfinite(before) & isfinite(after);
        partial(k) = dt*sum(0.5*before(available).^2+0.5*after(available).^2);
        coverage(k) = dt*nnz(available);
        if all(available(integrated))
            full(k) = partial(k);
        end
    end
    assert(all(isfinite(partial)), ...
        'rewardExposure:Overflow','Observed physical cost overflow; do not hide it as missing.');
    sampleTimes = steps.current_sample_time(committed);
    current = steps.current_sample_A(committed);
    assert(isreal([sampleTimes;current]) && all(isfinite([sampleTimes;current])) && ...
        all(abs(sampleTimes-steps.time_before(committed))<=tol) && all(diff(sampleTimes)>0), ...
        'rewardExposure:Current','Committed samples must be finite at their captured step times.');
    intervals = diff(sampleTimes);
    adjacent = diff(find(committed))==1;
    intervalCharge = intervals.*(0.5*abs(current(1:end-1))+0.5*abs(current(2:end)));
    assert(all(isfinite(intervalCharge)) && isfinite(sum(intervalCharge)), ...
        'rewardExposure:Overflow','Current integral overflow.');
    support = sum(intervals(adjacent));
    assert(support<=duration+tol,'rewardExposure:Current','Sample support exceeds integrated time.');
    sampled = NaN;
    if numel(current)>=2
        sampled = sum(intervalCharge);
    end
    exposure = struct('schema','reward_exposure_components_v1', ...
        'attempts',n,'integrated_duration_s',duration,'physical_names',names, ...
        'known_squared_integrals',partial,'full_squared_integrals',full, ...
        'finite_coverage_s',coverage,'missing_coverage_s',duration-coverage, ...
        'physical_exposure_observed',duration>0,'physical_complete',all(isfinite(full)), ...
        'current_sample_count',numel(current),'current_pair_observed',numel(current)>=2, ...
        'within_window_sampled_charge_As',sampled, ...
        'adjacent_sample_charge_As',sum(intervalCharge(adjacent)), ...
        'adjacent_sample_support_s',support,'unsupported_current_duration_s',max(0,duration-support), ...
        'bridged_gap_count',nnz(~adjacent),'bridged_gap_duration_s',sum(intervals(~adjacent)), ...
        'bridged_gap_charge_As',sum(intervalCharge(~adjacent)), ...
        'full_window_charge_claim',false,'training_promoted',false, ...
        'scope','Known health sums are partial lower bounds when coverage is missing, not complete costs. Current quadrature uses within-window committed samples; adjacent support excludes missing-sample bridges, startup and endpoint tails. No cross-window charge reconstruction, physical energy claim, coefficient choice or missingness penalty.');
end
