function [window,terminal,audit] = reconstructWindow(chunks,cfg)
%reconstructWindow Rebuild progress, terminal identity and complete bridge window.
% Chunks are row-derived reductions, not archived outcome/window annotations.
    assert(~isempty(chunks) && numel(chunks)<=cfg.APPLY_EVERY, ...
        'phase3window:Chunks','Require the captured decision chunk range.');
    before = chunks{1}.before;
    control = chunks{1}.control;
    origin = before.decision_bookkeeping.initial_position_x;
    assert(abs(before.decision_bookkeeping.distance_m-max(0,before.Xt(1)-origin))<1e-8, ...
        'phase3window:Progress','Saved starting progress differs from captured position and mission origin.');
    outs = cell(size(chunks));
    terminal = '';
    for k = 1:numel(chunks)
        c = chunks{k};
        assert(c.context.chunk==k && isequaln(c.control,control), ...
            'phase3window:Control','Chunk order and supervisory control must be constant within a decision.');
        if k>1
            previous = chunks{k-1}.after;
            assert(previous.t==c.before.t && isequaln(previous.Xt,c.before.Xt) && ...
                isequaln(previous.Ut,c.before.Ut) && isequaln(previous.battery,c.before.battery) && ...
                isequal(previous.current_time,c.before.current_time) && isequal(previous.current_total,c.before.current_total), ...
                'phase3window:Continuity','Decision chunk endpoints are discontinuous.');
        end
        distance = max(0,c.after.Xt(1)-origin);
        [terminal,done] = resolve_phase3_terminal(c.after,c.out,distance,cfg);
        assert(~done || k==numel(chunks), ...
            'phase3window:AfterTerminal','A decision cannot contain chunks after its first terminal event.');
        outs{k} = c.out;
    end
    assert(done || numel(chunks)==cfg.APPLY_EVERY, ...
        'phase3window:ShortDecision','Nonterminal decisions require every supervisory chunk.');
    window = phase3_decision_window(before,chunks{end}.after,outs,control,cfg,terminal);
    audit = struct('version','captured_decision_window_reconstruction_v1', ...
        'chunks',numel(chunks),'terminal_reason',terminal,'is_done',done, ...
        'qp_rows',sum(cellfun(@(x) x.qp_solve_count,outs)), ...
        'saved_window_or_outcome_used',false,'battery_model_recomputed',false, ...
        'terminal_classifier_scope','Reapply the declared terminal rule to row-derived stop events and captured post-chunk state; no new physical safety threshold or QP infeasibility solve.');
end
