function [scales,audit] = scales(cfg)
%scales Unit/reference scales, not safety thresholds.
    assert(~cfg.BATTERY.use_pack_sizing && ~cfg.RANDOMIZE_REQUEST, ...
        'candidateReward:Configuration','Require fixed pack and fixed request context.');
    lowV = max(cfg.V_MIN,min(cfg.V_MAX,cfg.V_MIN+cfg.GAMMA_V_MIN*(cfg.V_MAX-cfg.V_MIN)));
    highV = max(cfg.V_MIN,min(cfg.V_MAX,cfg.V_MIN+cfg.GAMMA_V_MAX*(cfg.V_MAX-cfg.V_MIN)));
    monotone = cfg.TACC_MAX>=cfg.TACC_MIN && cfg.TACC_MIN>0 && cfg.A_MIN<=cfg.A_MAX && ...
        lowV/cfg.TACC_MIN>=cfg.A_MIN && highV/cfg.TACC_MAX<=cfg.A_MAX;
    assert(monotone,'candidateReward:AccelerationBound','Governor corner maximum is not justified.');
    [~,maxA] = apply_command_governor(cfg.V_REQ_FIXED,cfg.A_REQ_FIXED, ...
        cfg.GAMMA_V_MAX,cfg.GAMMA_A_MAX,cfg);
    maxGammaDelta = min(cfg.DGAMMA_V_MAX,cfg.GAMMA_V_MAX-cfg.GAMMA_V_MIN);
    scales = struct('mission_duration_s',cfg.MISSION_DURATION,'target_distance_m',cfg.MISSION.D_TARGET_M, ...
        'charge_budget_As',3600*cfg.BATTERY.C_nom_Ah*cfg.BATTERY.n_parallel* ...
        (cfg.BATTERY.SOC_init-cfg.BATTERY.terminal_margin), ...
        'orientation_rad',1,'omega_rad_s',1,'velocity_error_m_s',1, ...
        'dR_max',cfg.DR_MAX,'delta_gamma_v_max',maxGammaDelta, ...
        'delta_v_max',maxGammaDelta*(cfg.V_MAX-cfg.V_MIN),'acceleration_max',maxA);
    validateattributes(struct2array(scales),{'double'},{'real','finite','positive'});
    audit = struct('schema','reward_candidate_reference_scales_v1', ...
        'physical_scales_are_unit_references_not_limits',true,'safety_calibrated',false, ...
        'charge_scope','Nominal fixed-pack Coulomb budget, not exact predicted battery-terminal charge.', ...
        'action_scope','Legal applied dR and gamma-rate ranges; velocity bound assumes consistent previous governor state; fixed-request monotone acceleration corner bound.', ...
        'coefficient_selection_performed',false);
end
