function [reward,info] = scoreComplete(c,policy)
%scoreComplete Explicitly weighted, offline candidate reward.
% No default coefficients, no implicit missing-health fallback or promotion.
    assert(strcmp(c.version,'reward_phase3_factored_candidate_v1') && ...
        strcmp(policy.version,'reward_phase3_factored_policy_v1'), ...
        'candidateReward:Version','Require named component and policy versions.');
    assert(isequal(string(policy.cost_names),c.cost_names) && ...
        isequal(string(policy.terminal_categories),c.terminal_categories), ...
        'candidateReward:Names','Weights must explicitly name every cost and terminal.');
    validateattributes(policy.cost_weights,{'double'},{'size',size(c.costs),'real','finite','nonnegative'});
    assert(~(policy.cost_weights(8)>0 && policy.cost_weights(9)>0), ...
        'candidateReward:RedundantCosts','Choose gamma or velocity slew cost, not both collinear proxies.');
    validateattributes(policy.terminal_values,{'double'},{'size',size(c.terminal_indicators),'real','finite'});
    validateattributes([policy.pace_weight,policy.recovered_event_cost],{'double'},{'real','finite','nonnegative','numel',2});
    assert(policy.terminal_values(1)>=0 && all(policy.terminal_values(2:end)<=0), ...
        'candidateReward:TerminalSigns','Completion cannot be a penalty and failure cannot be a bonus.');
    assert(isfield(policy,'rationale') && strlength(string(policy.rationale))>0, ...
        'candidateReward:Rationale','Explicit coefficient provenance/rationale is required.');
    choice = find(c.pace_names==string(policy.pace_name));
    assert(isscalar(choice),'candidateReward:Pace','Select one explicit pace alternative.');
    assert(c.physical_costs_available && all(isfinite(c.costs)), ...
        'candidateReward:MissingHealth','Do not silently reward transitions with missing physical costs.');
    penalties = c.costs.*policy.cost_weights;
    pace = c.pace_values(choice)*policy.pace_weight;
    terminal = c.terminal_indicators*policy.terminal_values.';
    recovered = c.recovered_solver_events*policy.recovered_event_cost;
    reward = pace-sum(penalties)+terminal-recovered;
    assert(isfinite(reward),'candidateReward:Nonfinite','Reward overflow.');
    info = struct('version',c.version,'policy',policy,'weighted_costs',penalties, ...
        'pace_contribution',pace,'terminal_contribution',terminal, ...
        'actual_terminal_reason',c.terminal_reason,'recovered_event_cost',recovered, ...
        'training_promoted',false,'calibrated_dynamic_safety',false);
end
