function [reward,info] = scoreCoverage(c,exposure,policy)
%scoreCoverage Finite invalid-terminal candidate with audit.
% Complete-data v1 scoring is preserved except that invalid terminals never
% receive positive pace credit. Partial health is allowed ONLY at invalid_state.
    assert(strcmp(c.version,'reward_phase3_factored_candidate_v1') && ...
        strcmp(policy.version,'reward_phase3_coverage_policy_v1') && ...
        strcmp(policy.invalid_state_mode,'known_costs_missing_exposure_no_positive_pace') && ...
        strcmp(exposure.schema,'reward_exposure_components_v1'), ...
        'coverageReward:Version','Require explicit coverage policy and exposure schema.');
    assert(isequal(exposure.physical_names,["orientation","omega","velocity_error"]), ...
        'coverageReward:Names','Physical exposure order must be explicit.');
    validateattributes(policy.missing_health_weights,{'double'}, ...
        {'size',[1,3],'real','finite','positive'});
    validateattributes(exposure.known_squared_integrals,{'double'}, ...
        {'size',[1,3],'real','finite','nonnegative'});
    validateattributes(exposure.finite_coverage_s,{'double'}, ...
        {'size',[1,3],'real','finite','nonnegative'});
    validateattributes(exposure.missing_coverage_s,{'double'}, ...
        {'size',[1,3],'real','finite','nonnegative'});
    assert(abs(exposure.integrated_duration_s-c.duration_s)<=1e-8 && ...
        all(abs(exposure.finite_coverage_s+exposure.missing_coverage_s-c.duration_s)<=1e-8), ...
        'coverageReward:Duration','Exposure must partition the same integrated decision duration.');
    missing = exposure.missing_coverage_s>0;
    assert(all(exposure.known_squared_integrals(exposure.finite_coverage_s==0)==0), ...
        'coverageReward:Integral','No integral may be invented without finite exposure.');
    terminal = string(c.terminal_reason);
    assert(isscalar(terminal) && (terminal=="" || any(terminal==c.terminal_categories)) && ...
        isequal(c.terminal_indicators,double(terminal==c.terminal_categories)), ...
        'coverageReward:Terminal','Terminal identity and indicators must agree.');
    invalid = terminal=="invalid_state";
    assert(isscalar(invalid) && (~any(missing) || invalid), ...
        'coverageReward:MissingNonterminal','Missing health requires an explicit invalid-state terminal; do not relabel it.');
    physical = c.costs(1:3);
    assert(isequal(logical(c.physical_costs_available),~any(missing)) && ...
        isequal(logical(exposure.physical_complete),~any(missing)) && ...
        all(isnan(physical(missing))), ...
        'coverageReward:Availability','Original component availability must agree with captured coverage.');
    scales = [c.scales.orientation_rad,c.scales.omega_rad_s,c.scales.velocity_error_m_s];
    known = exposure.known_squared_integrals./(scales.^2*c.scales.mission_duration_s);
    complete = ~missing;
    assert(all(abs(physical(complete)-known(complete))<=1e-10*(1+abs(known(complete)))), ...
        'coverageReward:Integral','Complete physical costs differ from captured exposure.');
    invalidIndex = find(c.terminal_categories=="invalid_state");
    assert(isscalar(invalidIndex) && policy.base_policy.terminal_values(invalidIndex)<0, ...
        'coverageReward:InvalidPenalty','Invalid state must have a strictly negative terminal value.');
    scored = c;
    scored.costs(1:3) = known;
    % The v1 arithmetic is reused on explicit finite objective contributions,
    % not on a claim that missing physical exposure was measured as healthy.
    scored.physical_costs_available = true;
    originalPace = scored.pace_values;
    if invalid
        scored.pace_values = min(scored.pace_values,0);
    end
    [base,baseInfo] = phase3reward.scoreComplete(scored,policy.base_policy);
    missingCosts = exposure.missing_coverage_s/c.scales.mission_duration_s;
    missingPenalties = missingCosts.*policy.missing_health_weights;
    reward = base-sum(missingPenalties);
    assert(isfinite(reward) && (~invalid || reward<0), ...
        'coverageReward:Nonfinite','Require finite reward and strictly negative invalid transition.');
    info = struct('version','reward_phase3_coverage_candidate_v1','policy',policy, ...
        'weighted_known_costs',baseInfo.weighted_costs, ...
        'weighted_missing_exposure_costs',missingPenalties, ...
        'pace_contribution',baseInfo.pace_contribution, ...
        'positive_pace_removed',originalPace-scored.pace_values, ...
        'terminal_contribution',baseInfo.terminal_contribution, ...
        'actual_terminal_reason',terminal,'recovered_event_cost',baseInfo.recovered_event_cost, ...
        'physical_costs_complete',~any(missing),'exposure',exposure, ...
        'training_promoted',false,'calibrated_dynamic_safety',false, ...
        'scope','Explicit finite objective over known physical costs plus missing-duration penalties and separate terminals; no imputed health, missing-cost upper bound or calibrated safety claim. Coefficients still require preference/empirical validation.');
end
