function policy = unitPolicy(id)
%unitPolicy Explicit experimental hypothesis, never an automatic/default policy.
    assert(isscalar(string(id)) && string(id)=="unit_reference_experimental_v1", ...
        'phase3reward:PolicyId','Name the experimental hypothesis explicitly.');
    names = ["orientation_exposure","omega_exposure","tracking_exposure","modeled_charge", ...
        "dR1_change","dR2_change","dR3_change","gamma_v_change","velocity_command_change","acceleration_command"];
    terminals = ["mission_complete","time_limit","battery_terminal","dynamic_safety_violation", ...
        "numerical_solver_failure_unrecovered","mathematical_constraint_infeasible", ...
        "invalid_state","no_safe_action_available","unclassified_solver_failure"];
    base = struct('version','reward_phase3_factored_policy_v1','cost_names',names, ...
        'cost_weights',[ones(1,4),zeros(1,6)],'terminal_categories',terminals, ...
        'terminal_values',[1,0,0,-1,0,-1,-1,-1,0], ...
        'pace_name','schedule_delta_undiscounted','pace_weight',1,'recovered_event_cost',0, ...
        'rationale','Unit health/charge/completion hypothesis screened on 38 historical preferences. Numerical/recovered events have no added physical-failure penalty; lack of completion and executed costs remain. Unobserved physical/invalid/no-action terminal values are explicit experimental unit-loss conventions, not calibrated limits.');
    policy = struct('version','reward_phase3_coverage_policy_v1','policy_id',char(id), ...
        'base_policy',base,'missing_health_weights',ones(1,3), ...
        'invalid_state_mode','known_costs_missing_exposure_no_positive_pace', ...
        'unobserved_conventions','Unit loss for dynamic/mathematical/invalid/no-safe-action terminals; unit missing-duration weights. No extra timeout/battery/solver penalty. These conventions require experimental review.', ...
        'training_promoted',false,'calibrated_dynamic_safety',false);
end
