function validatePolicy(policy,cfg)
%validatePolicy Check the full explicit policy before creating capture artifacts.
    assert(isstruct(policy) && isscalar(policy) && isfield(policy,'policy_id') && ...
        isscalar(string(policy.policy_id)) && strlength(string(policy.policy_id))>0 && ...
        isfield(policy,'unobserved_conventions') && isscalar(string(policy.unobserved_conventions)) && ...
        strlength(string(policy.unobserved_conventions))>0 && ...
        isfield(policy,'training_promoted') && isequal(policy.training_promoted,false), ...
        'phase3reward:Policy','Require a named unpromoted policy with explicit unobserved-terminal conventions.');
    scales = phase3reward.scales(cfg);
    w = struct('duration_s',0,'window_distance_m',0,'distance_start_m',0, ...
        'distance_end_m',0,'charge_As',0,'terminal_reason','','recovered_solver_events',0);
    x = struct('R_before',ones(3,1),'R_applied',ones(3,1),'delta_gamma_v_applied',0,'delta_v_exec',0,'a_exec',0);
    h = struct('integrated_duration_s',0,'orientation_squared_integral_observed',0, ...
        'omega_squared_integral_observed',0,'velocity_error_squared_integral_observed',0, ...
        'orientation_finite_coverage_s',0,'omega_finite_coverage_s',0,'velocity_error_finite_coverage_s',0);
    c = phase3reward.components(w,x,h,scales);
    e = struct('schema','reward_exposure_components_v1','physical_names',["orientation","omega","velocity_error"], ...
        'integrated_duration_s',0,'known_squared_integrals',zeros(1,3),'finite_coverage_s',zeros(1,3), ...
        'missing_coverage_s',zeros(1,3),'physical_complete',true);
    phase3reward.scoreCoverage(c,e,policy);
end
